repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet format Scripts.csproj --no-restore --verbosity diagnostic --include "$@"
        language: system
        files: ^Assets/Scripts/.*\.cs$