name: Unity Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  edit-mode:
    name: Run EditMode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Run Unity Edit Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.1.12f1
          testMode: EditMode
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}

      - name: Upload Edit Mode Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: EditMode-test-results
          path: ${{steps.RunUnityEditModeTests.outputs.coveragePath}}

  play-mode:
    name: Run PlayMode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Run Unity Play Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.1.12f1
          testMode: PlayMode
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}

      - name: Upload Play Mode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-test-results
          path: artifacts
