name: Unity Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  no-compile-errors:
    name: Check for Compile Errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-
      - name: Check for compile errors
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.1.12f1
          targetPlatform: StandaloneLinux64
          allowDirtyBuild: true
          buildMethod: ""
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}

  edit-mode:
    name: Run EditMode Tests
    runs-on: ubuntu-latest
    needs: no-compile-errors

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Run Unity Edit Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.1.12f1
          testMode: EditMode
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}

      - name: Upload Edit Mode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: EditMode-test-results
          path: artifacts

  play-mode:
    name: Run PlayMode Tests
    runs-on: ubuntu-latest
    needs: no-compile-errors

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Unity Packages
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-

      - name: Run Unity Play Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.1.12f1
          testMode: PlayMode
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}

      - name: Upload Play Mode Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-test-results
          path: artifacts

  linter-checks:
    name: Run Linter Checks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Lint C# Code Style
        uses: actions/setup-dotnet@v4
        with:
        dotnet-version: 8.0.x
        
      - name: Run dotnet format
        run: |
          dotnet tool install -g dotnet-format
          dotnet format --verify-no-changes --severity error

